### ISSUE TITLE
check links in scope tutorial

### ISSUE THREAD

**Issue by Thecave3** [open-5g/openrangym#10]
The links of coloran and scope (the ones I tested) are wrong and redirects to 404

Moreover, it would be nice to share the password containers of the common images maybe

**Comment by Thecave3** [comment]
https://github.com/wineslab/colosseum-scope-e2
pwd is `scope` we should kinda integrate these info in the tutorial to avoid emails and wasting time into replying to ppl

**Comment by raoulraft** [comment]
oai containers (`oai-core` `oai-gnb-e2agent` `oai-ric`) password is `pass`.

The core network in the `oai-core` SRN is started via 
`cd oai-cn5g-fed/docker-compose`
`./core-network.sh start nrf spgwu` 
instead of 
`./start_core.sh`

When trying to start the xApp container in the `oai-ric` SRN, a typo inside `radio_code/colosseum-near-rt-ric/setup-scripts/setup-base-xapp.sh` creates some issues. Therefore execute
`cd radio_code/colosseum-near-rt-ric/setup-scripts`
`nano setup-base-xapp.sh` 
and delete in line 68 the `à` that can be found in the path in the command `docker exec ${CONTAINER_NAME} sed -i "s/export XAPP_ID.*/export XAPP_ID=${XAPP_ID}/g" /home/xapp-oai/xapp-sm-connector/build_xapp.shà`.

**Comment by leonardobonati** [comment]
- Fixed broken links
- Added missing credentials
- Fixed the bad character issue in the LXC container itself

**Comment by Thecave3** [comment]
Closing this since it has been solved in 4d461eb1f06aa77286695ed67f2bef049430d168 3db3a851551d911e53e294b3148996afee1c3c06 74ee5f253f9ea0eda2e575cc553f1ba3ae089483.
